# Generated by Django 2.2.1 on 2019-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190621_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='avatars/covers/default.jpg', upload_to='avatars/covers/'),
        ),
    ]
