# Generated by Django 2.2.1 on 2019-06-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
