# Generated by Django 2.2.1 on 2019-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190622_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='covers/default.jpg', upload_to='posts/'),
        ),
    ]
