# Generated by Django 2.2.1 on 2019-05-29 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('date_serialized', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField()),
                ('latest', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
