# Generated by Django 2.2.1 on 2019-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
