# Generated by Django 2.2.1 on 2019-06-21 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190529_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
